import numpy as np
import hashlib
from Crypto.Hash import SHAKE128

zetas1 = np.array([1,1729,2580,3289,2642,630,1897,848,1062,
                 1919,193,797,2786,3260,569,1746,296,2447,
                 1339,1476,3046,56,2240,1333,1426,2094,535,
                 2882,2393,2879,1974,821,289,331,3253,1756,
                 1197,2304,2277,2055,650,1977,2513,632,2865,
                 33,1320,1915,2319,1435,807,452,1438,2868,
                 1534,2402,2647,2617,1481,648,2474,3110,
                 1227,910,17,2761,583,2649,1637,723,2288,
                 1100,1409,2662,3281,233,756,2156,3015,
                 3050,1703,1651,2789,1789,1847,952,1461,
                 2687,939,2308,2437,2388,733,2337,268,641,
                 1584,2298,2037,3220,375,2549,2090,1645,
                 1063,319,2773,757,2099,561,2466,2594,2804,
                 1092,403,1026,1143,2150,2775,886,1722,
                 1212,1874,1029,2110,2935,885,2154])

zetas2 = np.array([17,-17,2761,-2761,583,-583,2649,-2649,
                   1637,-1637,723,-723,2288,-2288,1100,
                   -1100,1409,-1409,2662,-2662,3281,-3281,
                   233,-233,756,-756,2156,-2156,3015,-3015,
                   3050,-3050,1703,-1703,1651,-1651,2789,
                   -2789,1789,-1789,1847,-1847,952,-952, 
                   1461,-1461,2687,-2687,939,-939,2308,
                   -2308,2437,-2437,2388,-2388,733,-733,
                   2337,-2337,268,-268,641,-641,1584,-1584,
                   2298,-2298,2037,-2037,3220,-3220,375,
                   -375,2549,-2549,2090,-2090,1645,-1645,1063,
                   -1063,319,-319,2773,-2773,757,-757,2099,
                   -2099,561,-561,2466,-2466,2594,-2594, 2804,
                   -2804,1092,-1092,403,-403,1026,-1026, 1143,
                   -1143,2150,-2150,2775,-2775,886,-886, 1722,
                   -1722,1212,-1212,1874,-1874,1029,-1029,
                   2110,-2110,2935,-2935,885,-885,2154,-2154])

def rounded(x):
    if abs(x % 1) == 0.5:
        return int(x + 0.5 if x > 0 else x - 0.5)
    else:
        return(round(x))

# This class was generated by ChatGPT since I didn't 
# understand what was going on here.
class XOF:
    @staticmethod
    def Init():
        return SHAKE128.new()
    
    @staticmethod 
    def Absorb(ctx, data: bytes):
        ctx.update(data)
        return ctx
    
    @staticmethod 
    def Squeeze(ctx, n_bytes: int) -> bytes:
        return ctx.read(n_bytes)

# Takes in one variable-length input and produces one
# 32-byte output.
def H(s):
    return(hashlib.sha3_256(s).digest())

# Takes in one variable-length input and produces one
# 32-byte output.
def J(s):
    return(hashlib.shake_256(s).digest(32))

# Takes in one variable-length input and produces two
# 32-byte outputs. 
def G(c):
    digested = hashlib.sha3_512(c).digest()
    a = digested[:32]
    b = digested[32:]
    return a, b

# Takes in a parameter eta (either 2 or 3), one 32-byte,
# input, and one 1-byte input. Produces one (64 x eta)-
# byte output.
def PRF(s, b, eta):
    return(hashlib.shake_256(s + b).digest(64*eta))

# Converts a bit array into an array of bytes.
def BitsToBytes(b):
    l = len(b)//8
    B = np.zeros(l, dtype = np.uint8)
    for i in range(0, len(b)):
        B[i//8] = B[i//8] + b[i]*2**(i % 8)
    return(B)

# Converts a byte array into a bit array.
def BytesToBits(B):
    if type(B) != np.ndarray:
        C = np.frombuffer(B, dtype = np.uint8).copy()
    else:
        C = B.copy()
    l = len(B)
    b = np.zeros(l*8, dtype = np.uint8)
    for i in range(0, len(B)):
        for j in range(0, 8):
            b[8*i + j] = C[i] % 2
            C[i] = C[i]//2
    return(b)

# Takes in a 12-bit integer. (Since q = 3329, the bit length of q is 12.). 
# Returns a d-bit compressed version of the number.
def Compress(x,d):
    return(rounded((2**d/3329)*x) % (2**d))

# Takes a d-bit compressed number and returns the full 12-bit
# version.
def Decompress(y,d):
    return(rounded(3329/(2**d)*y))

# Encodes an array of 256 d-bit integers into a byte array. Takes in
# an integer array F in Z_m where m = 2^d and d < 12 or m = q if d = 12.
# Outputs a byte array B of length 32*d. What it really does is convert from
# integers to bits, and then uses BitsToBytes() to convert from bits to bytes.
def ByteEncode(F, d):
    b = np.zeros(256*d, dtype = np.uint8)
    for i in range(0, 256):
        a = F[i]
        for j in range(0, d):
            b[i*d + j] = a % 2
            a = (a - b[i*d + j])//2
    B = BitsToBytes(b)
    return(B)

# Decodes a byte array into an array of d-bit integers for 1 <= d <= 12.
# Takes in a byte array and produces an integer array.
def ByteDecode(B, d):
    if d < 12:
        m = 2**d
    elif d == 12:
        m = 3329
    F = np.zeros(256, dtype = int)
    b = BytesToBits(B).astype(np.int16)
    for i in range(0,256):
        summation = 0 
        for j in range(0, d):
            summation += (b[i*d + j]*2**j)
        F[i] = summation % m
    return(F)

# Need a bit reversal function. I'm almost certain this function was ChatGPT 
# because there is no pseudocode for this in the standard.
def BitRev7(r):
    m = 0
    for i in range(7):
        m = (m << 1) | (r & 1)  # take LSB of r, shift into m
        r >>= 1
    return m


# Function that takes in a 32-byte seed and two additional indices as input,
# and outputs a pseudorandom element of T_q. This is akin to a uniform
# sampling of T_q.
def SampleNTT(B):
    ctx = XOF.Init()
    ctx = XOF.Absorb(ctx, B)
    j = 0
    a_hat = np.zeros(256, dtype = int)
    while j < 256:
        C = XOF.Squeeze(ctx,3)
        d_1 = C[0] + 256*(C[1] % 16)
        d_2 = (C[1]//16) + 16*C[2]
        if d_1 < 3329:
            a_hat[j] = d_1
            j = j + 1
        if d_2 < 3329 and j < 256:
            a_hat[j] = d_2
            j = j + 1
    return(a_hat)

# Now, we want to be able to sample from a distribution of polynomials
# in R_q, which we denote D_eta(R_q), of small coefficients. Each of the coefficients
# is randomly and independently sampled from a centered binomial distribution (CBD) on Z_q.
# This function, therefore, takes a seed and outputs a pseudorandom sample from said 
# distribution.
def SamplePolyCBD(B, eta):
    f = np.zeros(256, dtype = int)
    b = BytesToBits(B).astype(np.int16)
    for i in range(0, 256):
        summation_x = 0
        for j in range(0, eta):
            summation_x += b[2*i*eta + j]
        summation_y = 0
        for j in range(0, eta):
            summation_y += b[2*i*eta + eta + j]
        f[i] = (summation_x - summation_y) % 3329
    return(f)


# Function to compute the NTT representation of a polynomial in R_q.
# Takes in a numpy array and returns a numpy array.
def NTT(f, zetas1 = zetas1):
    f_hat = f.copy()
    i = 1
    length = 128
    while length >= 2:
        start = 0
        while start < 256:
            zeta = zetas1[i]
            i = i + 1 
            for j in range(start, start + length):
                t = (zeta*f_hat[j + length]) % 3329
                f_hat[j + length] = (f_hat[j] - t) % 3329
                f_hat[j] = (f_hat[j] + t) % 3329
            start = start + 2*length
        length = length // 2
    return(f_hat)

# Function to compute f from f_hat. Takes in a numpy array
# and returns a numpy array.
def INTT(f_hat, zetas1 = zetas1):
    f = f_hat.copy()
    i = 127
    length = 2 
    while length <= 128:
        start = 0
        while start < 256:
            zeta = zetas1[i]
            i = i - 1 
            for j in range(start, start + length):
                t = f[j]
                f[j] = (t + f[j + length]) % 3329
                f[j + length] = (zeta*(f[j + length] - t)) % 3329
            start = start + 2*length
        length = 2*length
    f = (f*3303) % 3329
    return(f)

# Computes the product of two degree-one polynomials in a ring mod q.
# Takes in the coefficients of (a_0 + a_1X) and (b_0 + b_1X), as well as
# gamma from the modulus (X^2 - gamma). 
def BaseCaseMultiply(a_0, a_1, b_0, b_1, gamma):
    a_0, a_1, b_0, b_1, gamma = map(int, (a_0, a_1, b_0, b_1, gamma))
    a_0 = a_0 % 3329
    a_1 = a_1 % 3329
    b_0 = b_0 % 3329
    b_1 = b_1 % 3329
    gamma = gamma % 3329
    c_00 = (a_0 * b_0) % 3329
    c_01 = (a_1 * b_1 * gamma) % 3329
    c_0 = (c_00 + c_01) % 3329
    c_10 = (a_0 * b_1) % 3329
    c_11 = (a_1 * b_0) % 3329
    c_1 = (c_10 + c_11) % 3329
    return(c_0, c_1)

# Multiplies together two polynomials in NTT form. Takes in two numpy arrays 
# and returns a numpy array.
def MultiplyNTTs(f_hat, g_hat, zetas1 = zetas1):
    h_hat = np.zeros(256, dtype = int)
    for i in range(0, 128):
        h_hat[2*i], h_hat[2*i + 1] = BaseCaseMultiply(f_hat[2*i], f_hat[2*i + 1], g_hat[2*i], g_hat[2*i + 1], zetas2[i])
    return(h_hat)